"""initial_tables_v2

Revision ID: 8d4c03981910
Revises: 
Create Date: 2026-01-19 10:21:04.085281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # <--- ADD THIS


# revision identifiers, used by Alembic.
revision: str = '8d4c03981910'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notams_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fir', sa.String(length=4), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('notam_id', sa.String(length=20), nullable=False),
    sa.Column('text_raw', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notams_raw_fir'), 'notams_raw', ['fir'], unique=False)
    op.create_index(op.f('ix_notams_raw_id'), 'notams_raw', ['id'], unique=False)
    op.create_index(op.f('ix_notams_raw_notam_id'), 'notams_raw', ['notam_id'], unique=True)
    op.create_table('obstacles_parsed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notam_raw_id', sa.Integer(), nullable=False),
    sa.Column('obstacle_type', sa.String(length=50), nullable=False),
    sa.Column('height_agl', sa.Float(), nullable=True),
    sa.Column('height_amsl', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['notam_raw_id'], ['notams_raw.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notam_raw_id')
    )
    #op.create_index('idx_obstacles_parsed_geom', 'obstacles_parsed', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_obstacles_type', 'obstacles_parsed', ['obstacle_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index('idx_obstacles_type', table_name='obstacles_parsed')
    op.drop_index('idx_obstacles_parsed_geom', table_name='obstacles_parsed', postgresql_using='gist')
    op.drop_table('obstacles_parsed')
    op.drop_index(op.f('ix_notams_raw_notam_id'), table_name='notams_raw')
    op.drop_index(op.f('ix_notams_raw_id'), table_name='notams_raw')
    op.drop_index(op.f('ix_notams_raw_fir'), table_name='notams_raw')
    op.drop_table('notams_raw')
    # ### end Alembic commands ###
