"""clean_init

Revision ID: f8b1efa8c939
Revises: 
Create Date: 2026-01-21 12:24:33.819264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f8b1efa8c939'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obstacles_parsed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notam_id', sa.String(length=20), nullable=False),
    sa.Column('fir', sa.String(length=4), nullable=True),
    sa.Column('obstacle_type', sa.String(length=50), nullable=True),
    sa.Column('min_fl', sa.Integer(), nullable=True),
    sa.Column('max_fl', sa.Integer(), nullable=True),
    sa.Column('radius_nm', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_obstacle_type_dates', 'obstacles_parsed', ['obstacle_type', 'start_date', 'end_date'], unique=False)
   # op.create_index('idx_obstacles_parsed_geom', 'obstacles_parsed', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_obstacles_parsed_end_date'), 'obstacles_parsed', ['end_date'], unique=False)
    op.create_index(op.f('ix_obstacles_parsed_fir'), 'obstacles_parsed', ['fir'], unique=False)
    op.create_index(op.f('ix_obstacles_parsed_id'), 'obstacles_parsed', ['id'], unique=False)
    op.create_index(op.f('ix_obstacles_parsed_notam_id'), 'obstacles_parsed', ['notam_id'], unique=True)
    op.create_index(op.f('ix_obstacles_parsed_obstacle_type'), 'obstacles_parsed', ['obstacle_type'], unique=False)
    op.create_index(op.f('ix_obstacles_parsed_start_date'), 'obstacles_parsed', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obstacles_parsed_start_date'), table_name='obstacles_parsed')
    op.drop_index(op.f('ix_obstacles_parsed_obstacle_type'), table_name='obstacles_parsed')
    op.drop_index(op.f('ix_obstacles_parsed_notam_id'), table_name='obstacles_parsed')
    op.drop_index(op.f('ix_obstacles_parsed_id'), table_name='obstacles_parsed')
    op.drop_index(op.f('ix_obstacles_parsed_fir'), table_name='obstacles_parsed')
    op.drop_index(op.f('ix_obstacles_parsed_end_date'), table_name='obstacles_parsed')
    op.drop_index('idx_obstacles_parsed_geom', table_name='obstacles_parsed', postgresql_using='gist')
    op.drop_index('idx_obstacle_type_dates', table_name='obstacles_parsed')
    op.drop_table('obstacles_parsed')
    # ### end Alembic commands ###
